#spring.datasource.username=root
#spring.datasource.password=rootroot
#spring.datasource.url=jdbc:mysql://localhost:3306/spring_security?serverTimezone=Asia/Shanghai
## 帮助我们初始化
#spring.datasource.initialization-mode=always

spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 1
jwt:
  key: pKUdmdtI6Sh3JUwr7fbX1Bku1EjEFqFgnic8jPTVWUejAu0fXAv0SL5zvjOI


#  忽略鉴权URI
ignore:
  uri:
    - /api/v1/user/login/up
    - /api/v1/user/login/sms
